charts: Add default gadget namespace
Fixes 1dcced3cc2f9b534f6f4a8d7c1da09af315c7460

The helm installation keeps on failing with gadget-namespace not set.
This change ensure we have the default namespace set. Also,
it adds a job to test helm charts installtion to avoid such issues
in future.

Signed-off-by: Qasim Sarfraz <qasimsarfraz@microsoft.com>

diff --git a/.github/workflows/inspektor-gadget.yml b/.github/workflows/inspektor-gadget.yml
--- a/.github/workflows/inspektor-gadget.yml
+++ b/.github/workflows/inspektor-gadget.yml
@@ -1256,6 +1256,71 @@ jobs:
         name: gadget-charts-tgz
         path: charts/bin/*.tgz
 
+  test-helm-charts:
+    name: Test Helm charts
+    # level: 2
+    runs-on: ubuntu-latest
+    needs:
+      - package-helm-charts
+      - build-gadget-container-images
+    steps:
+    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+    - name: Install Helm
+      uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
+      with:
+        token: ${{ secrets.GITHUB_TOKEN }}
+    - name: Download Helm charts
+      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
+      with:
+        name: gadget-charts-tgz
+    - name: Setup minikube
+      uses: ./.github/actions/setup-minikube
+      with:
+        runtime: "docker"
+    - name: Set container repository and determine image tag
+      id: set-repo-determine-image-tag
+      uses: ./.github/actions/set-container-repo-and-determine-image-tag
+      with:
+        registry: ${{ env.REGISTRY }}
+        container-image: ${{ env.CONTAINER_REPO }}
+    - name: Get gadget-container-image-linux-amd64.tar from artifact.
+      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
+      with:
+        name: gadget-container-image-linux-amd64.tar
+        path: /home/runner/work/inspektor-gadget/
+    - name: Prepare minikube by loading gadget-container-image-linux-amd64.tar
+      env:
+        CONTAINER_REPO: ${{ steps.set-repo-determine-image-tag.outputs.container-repo }}
+        IMAGE_TAG: ${{ steps.set-repo-determine-image-tag.outputs.image-tag }}
+      run: |
+        # 'docker load' ensures the image is named correctly e.g podman has issues loading untagged images from archive
+        docker load -i /home/runner/work/inspektor-gadget/gadget-container-image-linux-amd64.tar
+        minikube image load "${CONTAINER_REPO}:${IMAGE_TAG}"
+    - name: Test Helm charts
+      # default shell is "bash -e {0}" which will fail-fast if the command returns a non-zero exit code
+      # See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
+      shell: bash {0}
+      run: |
+        # Install the Helm chart
+        helm install gadget gadget-*.tgz \
+          --namespace gadget --create-namespace \
+          --set image.repository=${{ steps.set-repo-determine-image-tag.outputs.container-repo }} \
+          --set image.tag=${{ steps.set-repo-determine-image-tag.outputs.image-tag }} \
+          --set image.pullPolicy=Never
+
+        # Validate the installation
+        kubectl rollout status daemonset/gadget --namespace gadget --timeout=60s
+        if [[ $? -ne 0 ]]; then
+          echo "DaemonSet gadget is not available"
+          kubectl get pods --namespace gadget
+          kubectl describe daemonset gadget --namespace gadget
+          kubectl logs -n gadget daemonset/gadget
+          exit 1
+        fi
+        
+        # Uninstall the chart
+        helm uninstall gadget --namespace gadget
+
   publish-helm-charts:
     name: Publish Helm charts
     # level: 1
